CREATE TABLE `CrawlerContent` (
  `QueueID` INTEGER NOT NULL PRIMARY KEY,
  `Text` text
);

CREATE TABLE `CrawlerQueue` (
  `ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `Date` DATE NOT NULL,
  `Name` TEXT DEFAULT '',
  `Attendees` INTEGER DEFAULT NULL,
  `Location` TEXT DEFAULT NULL,
  `SourceID` INTEGER DEFAULT NULL,
  `Source` TEXT NOT NULL UNIQUE DEFAULT '',
  `SourceHash` BLOB NOT NULL DEFAULT '\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0',
  `Origin` TEXT NOT NULL DEFAULT 'crawler',
  `Category` TEXT DEFAULT NULL,
  `AddedOn` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS `Category` ON `CrawlerQueue` (`Category`);

CREATE TABLE `Sources` (
  `ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `Source` TEXT NOT NULL UNIQUE DEFAULT '',
  `Location` TEXT DEFAULT NULL,
  `Enabled` BOOLEAN NOT NULL DEFAULT 1,
  `AddedOn` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LastCrawled` datetime DEFAULT NULL
);
